

name: 'Execução Manual'

on:
  workflow_dispatch:


jobs:
  e2e-testes:
  
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v4

  
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      
      - name: Instalando Yarn
        run: npm install -g yarn

    
      - name: Instalando dependências
        run: yarn

      - name: Executando Testes E2E
        run: yarn run  ./trabalho/trabalho-final.js

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
          name: relatorio
          path: ./playwright-report
